# Generated by Django 5.2 on 2026-01-20 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_telegram_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=32, unique=True, verbose_name="Код привязки")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("expires_at", models.DateTimeField(verbose_name="Дата истечения")),
                ("used_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата использования")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привязка Telegram",
                "verbose_name_plural": "Привязки Telegram",
                "ordering": ("-created_at",),
            },
        ),
    ]
