# Generated by Django 5.2 on 2026-01-20 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(max_length=100, verbose_name="Действие"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.PositiveSmallIntegerField(default=60, verbose_name="Длительность"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Периодичность выполнения привычки"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(default=False, verbose_name="Позитивная привычка"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Публичная привычка"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(max_length=100, verbose_name="Место"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Награда"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(verbose_name="Время выполнения привычки"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Пользователь"
            ),
        ),
    ]
