# Generated by Django 5.2 on 2026-01-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_action_alter_habit_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_reminder",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
